# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ledger < Formula
  desc "Append-only local memory ledger for AI agents"
  homepage "https://github.com/kaofelix/ledger"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kaofelix/ledger/releases/download/v0.1.0/ledger_0.1.0_darwin_amd64.tar.gz"
      sha256 "f6ca184ec52b0c227086c25d4a1913355493ddfa5b31999a3b65d5b9a19ee278"

      def install
        bin.install "ledger"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kaofelix/ledger/releases/download/v0.1.0/ledger_0.1.0_darwin_arm64.tar.gz"
      sha256 "670c80acbba1ef4b5a7f9133186d1e3ac733426e7b2f4da5bb1add85cc3fc138"

      def install
        bin.install "ledger"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/kaofelix/ledger/releases/download/v0.1.0/ledger_0.1.0_linux_amd64.tar.gz"
      sha256 "9bead805973e924a212fce63672103cad79a8f3419d1db22d1d134df1601ffea"
      def install
        bin.install "ledger"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/kaofelix/ledger/releases/download/v0.1.0/ledger_0.1.0_linux_arm64.tar.gz"
      sha256 "2061294d2c5f40989a549b71a29ae093dec5d84a5cbb76ce22a64f54934a8202"
      def install
        bin.install "ledger"
      end
    end
  end

  test do
    system bin/"ledger", "init"
    assert_path_exists testpath/".ledger/ledger.db"
  end
end
